const characters = [
"Monkey D. Luffy",
"Roronoa Zoro",
"Nami",
"Sanji",
"Trafalgar D. Water Law",
"Nico Robin",
"Boa Hancock",
"Carrot",
"Portgas D. Ace",
"Sabo",
"Yamato",
"Shanks",
"Corazon (Donquixote Rosinante)",
"Charlotte Katakuri",
"Usopp",
"Tony Tony Chopper",
"Crocodile",
"Jinbe",
"Marco",
"Donquixote Doflamingo",
"Vivi Nefertari",
"Franky",
"Brook",
"Perona",
"Dracule Mihawk",
"Enel",
"Big Mom (Charlotte Linlin)",
"Silvers Rayleigh",
"Buggy",
"Gol D. Roger",
"Smoker",
"Kaido",
"Kozuki Oden",
"Vinsmoke Reiju",
"Cavendish",
"Bartolomeo",
"Eustass Kid",
"Sengoku",
"Kuzan (Aokiji)",
"Borsalino (Kizaru)",
"Donquixote Doflamingo (as a child)",
"Rebecca",
"Sabo (as a child)",
"Nefertari Cobra",
"Bartholomew Kuma",
"Helmeppo",
"X Drake",
"Koby",
"Sengoku (as a younger man)",
"Koala",
"Bon Clay (Bentham)",
"Caesar Clown",
"Kin'emon",
"Tashigi",
"Cavendish (as Hakuba)",
"Vinsmoke Judge",
"Vinsmoke Ichiji",
"Vinsmoke Niji",
"Vinsmoke Yonji",
"Charlotte Pudding",
"Pedro",
"Charlotte Cracker",
"Charlotte Smoothie",
"Big Mom (young)",
"Germa 66 (as children)",
"Caribou",
"Gaimon",
"Hatchan",
"Wiper",
"Zeff",
"Shakuyaku",
"Sengoku (as a Fleet Admiral)",
"Rob Lucci",
"Iceburg",
"Paulie",
"Blueno",
"Kumadori",
"Kalifa",
"Jabra",
"Fukurou",
"Spandam",
"Hattori (Rob Lucci's pigeon)",
"Queen",
"King",
"Yamato (young)",
"Kiku (Okiku)",
"Izo",
"Kyoshiro (Denjiro)",
"Toko",
"Orochi",
"Hyogoro",
"Kanjuro",
"Ashura Doji (Shutenmaru)",
"Raizo",
"Shinobu",
"Kikunojo",
"Hiyori",
"Tama",
]

const verbs = [
"Revenge",
"Dream",
"Voyage",
"Scream",
"Kiss",
"Endurance",
"Love",
"Hate",
"Courage",
"Fear",
"Discovery",
"Protection",
"Sacrifice",
"Patience",
"Bravery",
"Healing",
"Wisdom",
"Strength",
"Resilience",
"Perseverance",
"Betrayal",
"Ambition",
"Loyalty",
"Triumph",
"Survival",
]

export function getRandomName() {
    return characters[Math.floor(Math.random() * characters.length)] + "'s " + verbs[Math.floor(Math.random() * verbs.length)]
}