const characters = [
    "Garp",
    "Marshall D. Teach",
    "Benn Beckman",
    "Black Beard",
    "White Beard",
    "Gold Roger",
    "Monkey D. Luffy",
    "Luffy",
    "Roronoa Zoro",
    "Zoro",
    "Nami",
    "Sanji",
    "Trafalgar D. Water Law",
    "Law",
    "Nico Robin",
    "Boa Hancock",
    "Carrot",
    "Portgas D. Ace",
    "Ace",
    "Sabo",
    "Yamato",
    "Shanks",
    "Corazon",
    "Charlotte Katakuri",
    "Usopp",
    "Tony Tony Chopper",
    "Crocodile",
    "Jinbe",
    "Marco",
    "Vivi Nefertari",
    "Franky",
    "Brook",
    "Perona",
    "Dracule Mihawk",
    "Enel",
    "Big Mom",
    "Scopper Gaban",
    "Silvers Rayleigh",
    "Buggy",
    "Gol D. Roger",
    "Smoker",
    "Kaido",
    "Kozuki Oden",
    "Vinsmoke Reiju",
    "Cavendish",
    "Bartolomeo",
    "Eustass Kid",
    "Sengoku",
    "Kuzan",
    "Aokiji",
    "Borsalino",
    "Kizaru",
    "Donquixote Doflamingo",
    "Rebecca",
    "Nefertari Cobra",
    "Bartholomew Kuma",
    "Helmeppo",
    "X Drake",
    "Koby",
    "Koala",
    "Bon Clay",
    "Caesar Clown",
    "Kin'emon",
    "Tashigi",
    "Vinsmoke Judge",
    "Vinsmoke Ichiji",
    "Vinsmoke Niji",
    "Vinsmoke Yonji",
    "Charlotte Pudding",
    "Pedro",
    "Charlotte Cracker",
    "Charlotte Smoothie",
    "Caribou",
    "Gaimon",
    "Hatchan",
    "Wiper",
    "Zeff",
    "Shakuyaku",
    "Rob Lucci",
    "Iceburg",
    "Paulie",
    "Blueno",
    "Kumadori",
    "Kalifa",
    "Jabra",
    "Fukurou",
    "Spandam",
    "Hattori",
    "Queen",
    "King",
    "Okiku",
    "Izo",
    "Denjiro",
    "Toko",
    "Orochi",
    "Hyogoro",
    "Kanjuro",
    "Shutenmaru",
    "Raizo",
    "Shinobu",
    "Kikunojo",
    "Hiyori",
    "Tama",
]

const verbs = [
    "Revenge",
    "Dream",
    "Voyage",
    "Scream",
    "Kiss",
    "Endurance",
    "Love",
    "Hate",
    "Courage",
    "Fear",
    "Discovery",
    "Protection",
    "Sacrifice",
    "Patience",
    "Bravery",
    "Healing",
    "Wisdom",
    "Strength",
    "Resilience",
    "Perseverance",
    "Betrayal",
    "Ambition",
    "Loyalty",
    "Triumph",
    "Survival",
]

export function getRandomName() {
    return characters[Math.floor(Math.random() * characters.length)] + "'s " + verbs[Math.floor(Math.random() * verbs.length)]
}